In [65]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [66]:
df=pd.read_csv("cleaned_creditdata.csv")

In [67]:
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
...,...,...,...,...,...,...,...,...,...,...,...,...
32566,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32567,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32568,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32569,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32570,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [68]:
df.duplicated().sum()

165

In [69]:
remove_dup= df.drop_duplicates()

In [70]:
remove_dup.count()

person_age                    32406
person_income                 32406
person_home_ownership         32406
person_emp_length             32406
loan_intent                   32406
loan_grade                    32406
loan_amnt                     32406
loan_int_rate                 32406
loan_status                   32406
loan_percent_income           32406
cb_person_default_on_file     32406
cb_person_cred_hist_length    32406
dtype: int64

In [71]:
df

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
1,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
2,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
3,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
4,21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2
...,...,...,...,...,...,...,...,...,...,...,...,...
32566,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32567,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32568,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32569,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32570,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [72]:
df["loan_int_rate"] = df["loan_int_rate"].fillna(df["loan_int_rate"].median())
df["person_emp_length"] = df["person_emp_length"].fillna(df["person_emp_length"].median())

In [73]:
df.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [ ]:
X=df[["person_age","person_income","person_emp_length","loan_amnt","loan_int_rate","cb_person_cred_hist_length"]]
Y=df["loan_status"]

In [75]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [76]:
from sklearn.preprocessing import StandardScaler
scale=StandardScaler()
X_train_transformed=pd.DataFrame(scale.fit_transform(X_train),columns=X_train.columns,index=X_train.index)
X_test_transformed=pd.DataFrame(scale.fit_transform(X_test),columns=X_test.columns,index=X_test.index)
print(X_train_transformed)

       person_age  person_income  person_emp_length  loan_amnt  loan_int_rate  \
28618   -0.113623      -0.313680          -0.694923   0.182233       0.801305
14461   -0.436177       0.835354           1.061203  -0.758079       0.457495
7622    -0.436177      -0.234436          -0.945798  -0.568436      -1.569685
26725    0.531485       0.874976          -0.694923  -0.568436      -1.170736
1043    -0.920008       0.331562           0.308578   1.327991       1.381889
...           ...            ...                ...        ...            ...
13123   -0.920008       0.449279           0.308578  -1.042543      -1.692938
19648    1.015316      -0.610844          -1.196673  -1.010936       0.081250
9845    -0.920008      -0.511789          -0.694923  -0.094329      -0.136063
10799   -0.436177      -0.472167           0.057702   0.063706       0.642374
2732    -0.436177      -0.377075           0.057702   0.379777       0.681296

       loan_percent_income  cb_person_cred_hist_length
28618             0.375102                    0.296554
14461            -1.218056                   -0.442284
7622             -0.562050                   -0.442284
26725            -1.124341                    0.050275
1043              0.468817                   -0.934843
...                    ...                         ...
13123            -1.311772                   -0.688564
19648            -0.749481                    0.050275
9845              0.562532                   -0.442284
10799             0.656247                   -0.934843
2732              0.843678                   -0.442284

[26056 rows x 7 columns]

In [77]:
X_train_transformed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 26056 entries, 28618 to 2732
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  26056 non-null  float64
 1   person_income               26056 non-null  float64
 2   person_emp_length           26056 non-null  float64
 3   loan_amnt                   26056 non-null  float64
 4   loan_int_rate               26056 non-null  float64
 5   loan_percent_income         26056 non-null  float64
 6   cb_person_cred_hist_length  26056 non-null  float64
dtypes: float64(7)
memory usage: 1.6 MB

In [78]:
X_test_transformed.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6515 entries, 8225 to 11460
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  6515 non-null   float64
 1   person_income               6515 non-null   float64
 2   person_emp_length           6515 non-null   float64
 3   loan_amnt                   6515 non-null   float64
 4   loan_int_rate               6515 non-null   float64
 5   loan_percent_income         6515 non-null   float64
 6   cb_person_cred_hist_length  6515 non-null   float64
dtypes: float64(7)
memory usage: 407.2 KB

In [79]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(X_train_transformed,Y_train)

DecisionTreeClassifier()

In [80]:
y_test_pred=classifier.predict(X_test_transformed)

In [81]:
DT_accuracy=(accuracy_score(Y_test,y_test_pred))
print(classification_report(Y_test,y_test_pred))
DT_accuracy

              precision    recall  f1-score   support

           0       0.86      0.85      0.85      5147
           1       0.46      0.49      0.48      1368

    accuracy                           0.77      6515
   macro avg       0.66      0.67      0.67      6515
weighted avg       0.78      0.77      0.78      6515

0.7725249424405218

In [82]:
from sklearn.neighbors import KNeighborsClassifier
KNclassifier=KNeighborsClassifier()
KNclassifier.fit(X_train_transformed,Y_train)

KNeighborsClassifier()

In [83]:
y_test_pred=KNclassifier.predict(X_test_transformed)
kn_accuracy=(accuracy_score(Y_test,y_test_pred))
print(classification_report(Y_test,y_test_pred))
kn_accuracy

              precision    recall  f1-score   support

           0       0.88      0.93      0.90      5147
           1       0.65      0.51      0.57      1368

    accuracy                           0.84      6515
   macro avg       0.76      0.72      0.74      6515
weighted avg       0.83      0.84      0.83      6515

0.8397544128933231

In [84]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()
classifier.fit(X_train_transformed,Y_train)

RandomForestClassifier()

In [85]:
y_test_pred=classifier.predict(X_test_transformed)
RF_accuracy=(accuracy_score(Y_test,y_test_pred))
print(classification_report(Y_test,y_test_pred))
RF_accuracy

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      5147
           1       0.74      0.54      0.63      1368

    accuracy                           0.86      6515
   macro avg       0.81      0.75      0.77      6515
weighted avg       0.86      0.86      0.86      6515

0.8640061396776669

In [86]:
from sklearn.svm import SVC
SVclassifier=SVC()
SVclassifier.fit(X_train_transformed,Y_train)

SVC()

In [87]:
y_test_pred=SVclassifier.predict(X_test_transformed)
SVC_accuracy=(accuracy_score(Y_test,y_test_pred))
print(classification_report(Y_test,y_test_pred))
SVC_accuracy

              precision    recall  f1-score   support

           0       0.86      0.96      0.91      5147
           1       0.73      0.41      0.52      1368

    accuracy                           0.84      6515
   macro avg       0.79      0.68      0.71      6515
weighted avg       0.83      0.84      0.83      6515

0.8435917114351497

In [88]:
from sklearn.ensemble import BaggingClassifier
BAclassifier=BaggingClassifier()
BAclassifier.fit(X_train_transformed,Y_train)

BaggingClassifier()

In [89]:
y_test_pred=BAclassifier.predict(X_test_transformed)
BA_accuracy=(accuracy_score(Y_test,y_test_pred))
print(classification_report(Y_test,y_test_pred))
BA_accuracy

              precision    recall  f1-score   support

           0       0.87      0.94      0.90      5147
           1       0.67      0.48      0.56      1368

    accuracy                           0.84      6515
   macro avg       0.77      0.71      0.73      6515
weighted avg       0.83      0.84      0.83      6515

0.8409823484267076

In [90]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression()
classifier.fit(X_train_transformed,Y_train)

LogisticRegression()

In [91]:
y_test_pred=classifier.predict(X_test_transformed)
log_accuracy=(accuracy_score(Y_test,y_test_pred))
print(classification_report(Y_test,y_test_pred))
log_accuracy

              precision    recall  f1-score   support

           0       0.85      0.95      0.90      5147
           1       0.67      0.39      0.49      1368

    accuracy                           0.83      6515
   macro avg       0.76      0.67      0.70      6515
weighted avg       0.82      0.83      0.81      6515

0.8313123561013047

In [92]:
from xgboost import XGBClassifier
xgb_classifier = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1, random_state=0, use_label_encoder=False, eval_metric='logloss')
xgb_classifier.fit(X_train_transformed, Y_train)

y_test_pred_xgb = xgb_classifier.predict(X_test_transformed)
xgb_accuracy = accuracy_score(Y_test, y_test_pred_xgb)
print(classification_report(Y_test, y_test_pred_xgb))
xgb_accuracy

c:\Users\GORAKH\AppData\Local\Programs\Python\Python312\Lib\site-packages\xgboost\training.py:199: UserWarning: [14:44:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      5147
           1       0.70      0.52      0.60      1368

    accuracy                           0.85      6515
   macro avg       0.79      0.73      0.75      6515
weighted avg       0.84      0.85      0.84      6515

0.8531082118188795

In [96]:
evaluation = pd.DataFrame({'Algorithms':['Logistic Regression','Decision Tree','Random Forest','SVC','KNN','Bagging','XGBoost'],"Accuracy":[log_accuracy,DT_accuracy,RF_accuracy,SVC_accuracy,kn_accuracy,BA_accuracy,xgb_accuracy]})

In [97]:
evaluation

            Algorithms  Accuracy
0  Logistic Regression  0.831312
1        Decision Tree  0.772525
2        Random Forest  0.864006
3                  SVC  0.843592
4                  KNN  0.839754
5              Bagging  0.840982
6              XGBoost  0.853108